
modLoader="javafml"
loaderVersion="[36.2.0,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/ArtyArticus/EcoRegions/issues"

[[mods]]
modId="ecoregions"
version="${file.jarVersion}"
displayName="Zawa: Eco-Regions Addon"
#updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/eco-regions"
logoFile="logo.png"
credits="Arty, HelloCrossy67, SpiggitySpag, Lleo, Arzher, Shoresy"
authors="HelloCrossy67"
description='''Explore your overworld to find new animals that come from the continents of our real world thru this mod!'''

[[dependencies.ecoregions]]
modId="forge"
mandatory=true
versionRange="[36.2.20,)"
ordering="NONE"
side="BOTH"

[[dependencies.ecoregions]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5-1.17)"
ordering="NONE"
side="BOTH"

[[dependencies.ecoregions]]
modId="zawa"
mandatory=true
versionRange="[1.16.5-1.0.2-BeefBeta-TropicalExpedition3,)"
ordering="AFTER"
side="BOTH"